### ISSUE TITLE
Error in main loop - key error 15

### ISSUE THREAD

**Issue by maxfield-allison** [christgau/wsdd#47] opened 2020-06-11 16:03 UTC
Hello, 
When running the script on Linux Mint 19.3 Cinnamon 5.6.4-050604-lowlatency I'm getting the error in the title no matter where I run the script and regardless of any options used. 
`administrator@Server-01:~$ ~/wsdd.py 
2020-06-11 10:59:48,038:wsdd WARNING(pid 49307): no interface given, using all interfaces
2020-06-11 10:59:48,454:wsdd ERROR(pid 49307): error in main loop
Traceback (most recent call last):
  File "/home/administrator/wsdd.py", line 1626, in main
    key.data.handle_request()
  File "/home/administrator/wsdd.py", line 1195, in handle_request
    iface = self.interfaces[ifa_idx]
KeyError: 15
`

**Comment by christgau** [comment] 2020-06-11 16:06
duplicate of #45

**Closed by christgau** 2020-06-11 16:06 UTC
Labels: duplicate

**Comment by maxfield-allison** [comment] 2020-06-11 16:12
ohp, gotchya, I read through the other issue and didn't notice the similarity. My bad and thanks for the quick response!
