### ISSUE TITLE
High CPU usage after server reboot

### ISSUE THREAD

**Issue by kevinkk525** [christgau/wsdd#59] opened 2020-09-11 05:17 UTC
I just rebooted my machine and even many minutes later, the wsdd.py is still using 100% cpu (one core):
![grafik](https://user-images.githubusercontent.com/9607123/92865494-abee8600-f3fe-11ea-821c-8bc861386a6f.png)

A restart of the wsdd service fixed the problem. I can't think of a reason for this to happen but I don't really know the source code.

**Comment by christgau** [comment] 2020-09-11 17:27
I presume you are using Linux. Is that correct?

**Comment by kevinkk525** [comment] 2020-09-11 18:01
yes, sorry. Ubuntu 20.04. wsdd installed using this how-to: https://devanswers.co/discover-ubuntu-machines-samba-shares-windows-10-network/

**Comment by christgau** [comment] 2020-09-12 08:31
If my intention is right, the issue may not be reproducible in a reliable fashion. Thus, if you reboot the CPU hogging may appear or it may not. It would be good thing to reboot several times in order to get an impression how often or how "reliable" the issue appears. _After_ that you can use the above commit (983a2f90c70) and replace `wsdd.py` on your machine with the one from the commit. You should then reboot again several times and have a look if the issue is gone (or at least happens not 
that often).

**Comment by kevinkk525** [comment] 2020-09-15 05:18
I tested it a few times and the CPU hogging occured on every reboot. With your commit the first reboot had no CPU hogging anymore. Will report back after a few more reboots but it'll take a few days, don't want to reboot too often.

**Comment by kevinkk525** [comment] 2020-09-21 05:04
I am now confident that the commit fixes my issue. thanks.

**Comment by ske5074** [comment] 2020-10-01 02:52
I have also been experiencing this issue and it's been repeatable.  A restart of the wsdd tends to resolve the issue.  
![image](https://user-images.githubusercontent.com/10581604/94759873-5141ad80-035e-11eb-95d4-c2064f746b22.png)

$ uname -a
Linux jarvis 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

I'm updating tonight and will report if there's improvement.  

Great utility - It makes all the difference on my Windows 10 systems at home easily accessing the Samba shared.

**Comment by ske5074** [comment] 2020-10-02 19:19
I'm sorry to report I'm still experiencing  the issue but it appears that it took somewhere between 12-24 hours to start misbehaving.

![image](https://user-images.githubusercontent.com/10581604/94957991-ffa73900-04ab-11eb-807c-4866b6bdb236.png)

**Comment by christgau** [comment] 2020-10-02 20:45
Too bad but thanks for bringing up the details. I've read about similar issues in some forums out here. 

My assumption is that it has to do with changes in network address. Handling such changes was one of the reasons for the major rewrite in version 0.5, but the actual and OS-dependent handling of such changes is PITA.

For finding the issue I propose to fire up a debugger, i.e. `gdb`, and check the stack trace. You can find details [here](https://wiki.python.org/moin/DebuggingWithGdb). If everything is installed (gdb and its python) attach to the python process running wsdd and issue a `py-bt` to get a back-trace of the python calls.  That is what I'm very interested in . Since wsdd is running as root you have to start gdb as root as well.

Ah,... and btw @kevinkk525 and @ske5074 Which architecture do your systems have? x84-64? Or something "exotic" like aarch64 (Raspberry Pi) or some ARM. If in doubt, `uname -m` will tell you.

**Comment by kevinkk525** [comment] 2020-10-02 20:48
x84-64, my network address and devices never change (except for docker networks but I run wsdd only on br0 so no changes there) and it has been fine since the commit. Multiple restarts and longer running periods without problems.
maybe the problem for @ske574 is that he runs wsdd on all interfaces?

**Comment by christgau** [comment] 2020-10-02 20:48
Sorry, @ske5074 just noticed you are x86_64.

**Comment by christgau** [comment] 2020-10-02 21:02
> x84-64, my network address and devices never change (except for docker networks but I run wsdd only on br0 so no changes there) 

Yeah, that might be true but the address change detection code does not care about the interfaces in the first place. It just handles all network changing messages that are sent by the kernel and this also includes generally all interfaces. Filtering is then done by wsdd on the application level. In addition, although you may not observe network address changes does not mean that the kernel is quite in that time, especially not when other addresses change on other interfaces occur. 

> and it has been fine since the commit. Multiple restarts and longer running periods without problems.

That's good to hear, but may be it is just coincidence... Looking forward what @ske5074 reports

**Comment by ske5074** [comment] 2020-10-02 21:19
Thanks @christgau - Yes on x86_64 - I'll work on getting some debug data.  I was going to just run python -dv wsdd and see if I could get any insight but I can fire up gdb.

@kevinkk525 does bring up 2 things - I am running on all interfaces and I am also running docker and every container state change seems to have a number of network  changes under the covers.  I'll try to reproduce the issue and run gdb first but I think I'll try binding it to the interface later to see if that helps as well.

**Comment by christgau** [comment] 2020-10-03 05:45
>  I'll try to reproduce the issue and run gdb first

That would be superb in order to find the real reason for this issue - not only a workaround 😉 Thanks in advance for your efforts!

**Comment by staticlama** [comment] 2021-01-05 04:17
+1 to this issue. Having the same problem on ubuntu 20.04 (running a bunch of docker containers as well). I've had to disable wsdd as I've moved my storage to unraid.

**Comment by christgau** [comment] 2021-01-05 06:35
@staticlama which version do you use on which architecture? Have you tried the mentioned [issue branch](https://github.com/christgau/wsdd/tree/issue-59)? If yes and the problem exists there too, I would very much appreciate a backtrace (see https://github.com/christgau/wsdd/issues/59#issuecomment-702949325) to get the location of the loop where wsdd is probably stuck.

**Comment by christgau** [comment] 2021-01-06 15:16
Another issue was raised - and fixed - meanwhile. It appears to be related to what you saw/see. You should try the latest master branch instead of the issue branch now and see if the problem is gone. Please let me know about your experiences.

**Comment by christgau** [comment] 2024-01-22 21:32
No feedback for about 3 three years. Closing this issue. Feel free to reopen in case the problem appears again

**Closed by christgau** 2024-01-22 21:32 UTC
Labels: need more infos
