### ISSUE TITLE
I am getting a "general error" when trying to install the gpg key

### ISSUE THREAD

**Issue by MACCAMCGOO** [christgau/wsdd#142] opened 2022-05-26 14:39 UTC
This is weird as I have two identical machines both on the same network sharing the same internet connection... installed the deb, key and wsdd without issue.
Tried on the other machine and I get the following  

#:~ sudo apt-key adv --fetch-keys https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key

Executing: /tmp/apt-key-gpghome.zMvzKMRig1/gpg.1.sh --fetch-keys https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key
gpg: requesting key from 'https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key'
gpg: WARNING: unable to fetch URI https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key: General error

any ideas?

**Comment by christgau** [comment] 2022-05-26 17:12
I can fetch the key without problems. Have to tried to download the key directly via curl, e.g, to see if download works in principle. If that does not work, the problem is not 

Btw: Which distro are you using? wsdd has landed in Jammy's universe (see #137). No need to install the third party repo there.

**Comment by christgau** [comment] 2022-08-25 14:27
Closing the issue after almost three months of silence.

**Closed by christgau** 2022-08-25 14:27 UTC
