### ISSUE TITLE
Server reboot [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by bwaindwain** [christgau/wsdd#23] opened 2020-01-04 19:47 UTC
I'm using Ubuntu 18.04 desktop for my samba shares. I've set wsdd up as a service and when I run `sudo systemctl start wsdd` it works great and I can see my server from my Windows 10 machine (Explorer > Network).

But when Ubuntu reboots, I can't see the share from Windows. See log below. I've done `systemctl daemon-reload`, `systemctl start wsdd` and `systemctl enable wsdd`. In the `wsdd.service` I'm using `User=nobody` and `Group=nogroup`.

When I run `systemctl start wsdd` (without `sudo`) it asks me for authentication. 

When I run `sudo systemctl status wsdd` it says `wsdd[1737]: WARNING: no interface given, using all interfaces`

Any ideas what I'm doing wrong?
```
wsdd[1332]: Traceback (most recent call last):
wsdd[1332]:   File "/usr/bin/wsdd", line 846, in <module>
wsdd[1332]:     sys.exit(main())
wsdd[1332]:   File "/usr/bin/wsdd", line 839, in main
wsdd[1332]:     retval = serve_wsd_requests(addresses)
wsdd[1332]:   File "/usr/bin/wsdd", line 782, in serve_wsd_requests
wsdd[1332]:     http_srv = klass(interface.listen_address, WSDHttpRequestHandler)
wsdd[1332]:   File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
wsdd[1332]:     self.server_bind()
wsdd[1332]:   File "/usr/bin/wsdd", line 64, in server_bind
wsdd[1332]:     super().server_bind()
wsdd[1332]:   File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
wsdd[1332]:     socketserver.TCPServer.server_bind(self)
wsdd[1332]:   File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
wsdd[1332]:     self.socket.bind(self.server_address)
wsdd[1332]: OSError: [Errno 99] Cannot assign requested address
systemd[1]: wsdd.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: wsdd.service: Failed with result 'exit-code'.
```

**Comment by bwaindwain** [comment] 2020-01-04 21:12
I tried adding `time.sleep(10) ` from https://github.com/christgau/wsdd/issues/18#issue-502916378 and now I can see the shares in Windows even after Ubuntu reboots. This is just a hack though.

**Comment by christgau** [comment] 2020-01-05 09:18
> I've done `systemctl daemon-reload`, `systemctl start wsdd` and `systemctl enable wsdd`. In the `wsdd.service` I'm using `User=nobody` and `Group=nogroup`.

That's ok.

> When I run `systemctl start wsdd` (without `sudo`) it asks me for authentication.

The request authentication is nothing that comes from wsdd but rather from systemd.

> When I run `sudo systemctl status wsdd` it says `wsdd[1737]: WARNING: no interface given, using all interfaces`

This is the output when you don't specify an interface as argument (`-i). It is meant to be a "heads up" since you might announce your host/shares on interfaces you don't want it to be announced. If there is no other message after that then wsdd is running fine.

> Any ideas what I'm doing wrong?

There seem to be no issues with your configuration or systemd setup. The whole problem appears to be a duplicate of #18. Therefore, I'm closing this one and would like to continue the discussion over there.

**Closed by christgau** 2020-01-05 09:18 UTC
