### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by nemihome** [christgau/wsdd#54] opened 2020-07-28 19:15 UTC
Hi,

I'm not sure if this is an issue. I'm using Ubuntu 20.04, Samba 4.11.6.

I have "installed" wsdd as a service but I also tried it manually. The NAS is showing up directly in Windows 10 after starting wsdd but when click on it I will get. "Error 0x80070035 Network path not found". Which means it is not possible to view the SMB folders. There are folders for named users and also for nobody / nogroup.

A direct connection with the IP is working without problems. I have several network interfaces in the NAS. I manually started wsdd with "wsdd --interface enp2s0 -4" but the result is still the same. Min proto in Samba is V3. The mentioned ports in the firewall are open on the NAS.

NAS Address: 192.168.179.9
Windows 10: 192.168.179.3

So basically this is looking like it is working, isn't it?

`Jul 28 21:01:33 od wsdd[1712205]: INFO: using pre-defined UUID b338304b-5023-5185-bfcc-997c88a99130
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: netlink message with 428 bytes
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 2
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 7 3
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 8
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 6
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address 127.0.0.1 on lo
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: ignoring that address on lo
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 2
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 4
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 11 3
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 8
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 6
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address 192.168.179.9 on enp2s0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: handling traffic for 192.168.179.9 on enp2s0
Jul 28 21:01:33 od wsdd[1712205]: INFO: joined multicast group ('239.255.255.250', 3702) on 192.168.179.9%enp2s0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: transport address on enp2s0 is 192.168.179.9
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: will listen for HTTP traffic on address ('192.168.179.9', 5357)
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: constructed xml for WSD message: b'<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsdp="http://schemas.xmlsoap.org/ws/2006/02/devprof" xmlns:pnpx="http://schemas.microsoft.com/windows/pnpx/2005/10" xmlns:pub="http://schemas.microsoft.com/windows/pub/2005/07"><soap:Header><wsa:To>urn:schemas-xmlsoap-org:ws:2005:04:discovery</wsa:To><wsa:Action>http://schemas.xmlsoap.org/ws/2005/04/discovery/Hello</wsa:Action><wsa:MessageID>urn:uuid:c0cf5d28-d104-11ea-886f-2dbf4c0140e3</wsa:MessageID><wsd:AppSequence InstanceId="1595962893" SequenceId="urn:uuid:c0cf5d29-d104-11ea-886f-2dbf4c0140e3" MessageNumber="0" /></soap:Header><soap:Body><wsd:Hello><wsa:EndpointReference><wsa:Address>urn:uuid:b338304b-5023-5185-bfcc-997c88a99130</wsa:Address></wsa:EndpointReference><wsd:XAddrs>http://192.168.179.9:5357/b338304b-5023-5185-bfcc-997c88a99130</wsd:XAddrs><wsd:MetadataVersion>1</wsd:MetadataVersion></wsd:Hello></soap:Body></soap:Envelope>'
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: scheduling Hello message via enp2s0 to ('239.255.255.250', 3702)
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 2
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 4
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 11 3
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 8
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 6
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address 192.168.181.102 on enp3s0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: ignoring that address on enp3s0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 2
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 4
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 3
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 8
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 6
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address 192.168.178.46 on enx000ec6633dec
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: ignoring that address on enx000ec6633dec
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 2
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 9 3
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address 10.8.0.1 on tun0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: ignoring that address on tun0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: netlink message with 432 bytes
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 6
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 8
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address ::1 on lo
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: ignoring that address on lo
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 6
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 8
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address fe80::21e:6ff:fe45:308a on enp2s0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: ignoring that address on enp2s0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 6
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 8
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address 2003:f0:3f3c:f353:21e:6ff:fe45:308b on enp3s0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: ignoring that address on enp3s0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 6
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 8
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address fe80::21e:6ff:fe45:308b on enp3s0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: ignoring that address on enp3s0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 6
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 8
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address fe80::20e:c6ff:fe63:3dec on enx000ec6633dec
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: ignoring that address on enx000ec6633dec
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 20 6
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: rt_attr 8 8
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: new address fe80::667a:72bb:6988:e54e on tun0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: ignoring that address on tun0
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: netlink message with 20 bytes
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: invalid rtm_message type 3
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: invalid rtm_message type 1
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: processing WSD Get message (urn:uuid:af3bf07a-2b88-488f-af4d-ed68315d2041)
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: incoming message content is b'<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"><soap:Header><wsa:To>urn:uuid:b338304b-5023-5185-bfcc-997c88a99130</wsa:To><wsa:Action>http://schemas.xmlsoap.org/ws/2004/09/transfer/Get</wsa:Action><wsa:MessageID>urn:uuid:af3bf07a-2b88-488f-af4d-ed68315d2041</wsa:MessageID><wsa:ReplyTo><wsa:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:Address></wsa:ReplyTo><wsa:From><wsa:Address>urn:uuid:10ca9acf-d4d3-4ca5-af28-e197a67beb7a</wsa:Address></wsa:From></soap:Header><soap:Body/></soap:Envelope>'
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: constructed xml for WSD message: b'<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsdp="http://schemas.xmlsoap.org/ws/2006/02/devprof" xmlns:pnpx="http://schemas.microsoft.com/windows/pnpx/2005/10" xmlns:pub="http://schemas.microsoft.com/windows/pub/2005/07"><soap:Header><wsa:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:To><wsa:Action>http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse</wsa:Action><wsa:MessageID>urn:uuid:c0cf5d2a-d104-11ea-886f-2dbf4c0140e3</wsa:MessageID><wsa:RelatesTo>urn:uuid:af3bf07a-2b88-488f-af4d-ed68315d2041</wsa:RelatesTo></soap:Header><soap:Body><wsx:Metadata><wsx:MetadataSection Dialect="http://schemas.xmlsoap.org/ws/2006/02/devprof/ThisDevice"><wsdp:ThisDevice><wsdp:FriendlyName>WSD Device od</wsdp:FriendlyName><wsdp:FirmwareVersion>1.0</wsdp:FirmwareVersion><wsdp:SerialNumber>1</wsdp:SerialNumber></wsdp:ThisDevice></wsx:MetadataSection><wsx:MetadataSection Dialect="http://schemas.xmlsoap.org/ws/2006/02/devprof/ThisModel"><wsdp:ThisModel><wsdp:Manufacturer>wsdd</wsdp:Manufacturer><wsdp:ModelName>wsdd</wsdp:ModelName><pnpx:DeviceCategory>Computers</pnpx:DeviceCategory></wsdp:ThisModel></wsx:MetadataSection><wsx:MetadataSection Dialect="http://schemas.xmlsoap.org/ws/2006/02/devprof/Relationship"><wsdp:Relationship Type="http://schemas.xmlsoap.org/ws/2006/02/devprof/host"><wsdp:Host><wsa:EndpointReference><wsa:Address>urn:uuid:b338304b-5023-5185-bfcc-997c88a99130</wsa:Address></wsa:EndpointReference><wsdp:Types>pub:Computer</wsdp:Types><wsdp:ServiceId>urn:uuid:b338304b-5023-5185-bfcc-997c88a99130</wsdp:ServiceId><pub:Computer>OD/Workgroup:WORKGROUP</pub:Computer></wsdp:Host></wsdp:Relationship></wsx:MetadataSection></wsx:Metadata></soap:Body></soap:Envelope>'
Jul 28 21:01:33 od wsdd[1712205]: INFO: 192.168.179.3 - - "POST /b338304b-5023-5185-bfcc-997c88a99130 HTTP/1.1" 200 -
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: processing WSD Get message (urn:uuid:b766b874-ed44-497f-a33c-0a607810c580)
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: incoming message content is b'<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"><soap:Header><wsa:To>urn:uuid:b338304b-5023-5185-bfcc-997c88a99130</wsa:To><wsa:Action>http://schemas.xmlsoap.org/ws/2004/09/transfer/Get</wsa:Action><wsa:MessageID>urn:uuid:b766b874-ed44-497f-a33c-0a607810c580</wsa:MessageID><wsa:ReplyTo><wsa:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:Address></wsa:ReplyTo><wsa:From><wsa:Address>urn:uuid:80a65d05-140e-47e8-9997-799db5a668eb</wsa:Address></wsa:From></soap:Header><soap:Body/></soap:Envelope>'
Jul 28 21:01:33 od wsdd[1712205]: DEBUG: constructed xml for WSD message: b'<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsdp="http://schemas.xmlsoap.org/ws/2006/02/devprof" xmlns:pnpx="http://schemas.microsoft.com/windows/pnpx/2005/10" xmlns:pub="http://schemas.microsoft.com/windows/pub/2005/07"><soap:Header><wsa:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:To><wsa:Action>http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse</wsa:Action><wsa:MessageID>urn:uuid:c0cf5d2b-d104-11ea-886f-2dbf4c0140e3</wsa:MessageID><wsa:RelatesTo>urn:uuid:b766b874-ed44-497f-a33c-0a607810c580</wsa:RelatesTo></soap:Header><soap:Body><wsx:Metadata><wsx:MetadataSection Dialect="http://schemas.xmlsoap.org/ws/2006/02/devprof/ThisDevice"><wsdp:ThisDevice><wsdp:FriendlyName>WSD Device od</wsdp:FriendlyName><wsdp:FirmwareVersion>1.0</wsdp:FirmwareVersion><wsdp:SerialNumber>1</wsdp:SerialNumber></wsdp:ThisDevice></wsx:MetadataSection><wsx:MetadataSection Dialect="http://schemas.xmlsoap.org/ws/2006/02/devprof/ThisModel"><wsdp:ThisModel><wsdp:Manufacturer>wsdd</wsdp:Manufacturer><wsdp:ModelName>wsdd</wsdp:ModelName><pnpx:DeviceCategory>Computers</pnpx:DeviceCategory></wsdp:ThisModel></wsx:MetadataSection><wsx:MetadataSection Dialect="http://schemas.xmlsoap.org/ws/2006/02/devprof/Relationship"><wsdp:Relationship Type="http://schemas.xmlsoap.org/ws/2006/02/devprof/host"><wsdp:Host><wsa:EndpointReference><wsa:Address>urn:uuid:b338304b-5023-5185-bfcc-997c88a99130</wsa:Address></wsa:EndpointReference><wsdp:Types>pub:Computer</wsdp:Types><wsdp:ServiceId>urn:uuid:b338304b-5023-5185-bfcc-997c88a99130</wsdp:ServiceId><pub:Computer>OD/Workgroup:WORKGROUP</pub:Computer></wsdp:Host></wsdp:Relationship></wsx:MetadataSection></wsx:Metadata></soap:Body></soap:Envelope>'
Jul 28 21:01:33 od wsdd[1712205]: INFO: 192.168.179.3 - - "POST /b338304b-5023-5185-bfcc-997c88a99130 HTTP/1.1" 200 -`

As you can see a direct connect to the ip is showing several folders:
[Screenshot](https://abload.de/image.php?img=samba25jgj.jpg)

Basically OD should work the same because it is the same IP.

**Comment by christgau** [comment] 2020-07-28 20:03
> The NAS is showing up directly in Windows 10 after starting wsdd 

Well, that's basically everything wsdd is responsible for... The host is shown as a small computer icon in Explorer's Network view. If that works, wsdd has successfully done its job.

> but when click on it I will get. "Error 0x80070035 Network path not found".

IMO, the name resolution does not work. You can try to ping the host, "od", from the command line. If that is not working, it's likely the cause for your problem. 

I'd would be nice if you share your solution to the problem here for the community, but wsdd appears to behave as intended. Thus, I'm closing that ticket.

**Closed by christgau** 2020-07-28 20:03 UTC
Labels: invalid

**Comment by nemihome** [comment] 2020-07-28 21:00
That was easier than expected. The ping idea pointed me the right direction. The NAS has 3 network adapters attached. This results in coflicts with the automatically used host name pointing to another IP (I'm not sure why this IP is used because it is not in the hosts file) which is not used for SMB. Using another hostname for wsdd via -h NAS solves the problem and is pointing to the right IP.
