### ISSUE TITLE
xml.etree.ElementTree.ParseError: unbound prefix: line 3, column 17

### ISSUE THREAD

**Issue by spindles7** [christgau/wsdd#124] opened 2021-11-26 21:29 UTC
I am running wsdd version 0.6.4 on a raspberry pi running raspbian buster.   I have started getting these messages in syslog:

```Nov 23 05:46:59 pi-backuppc wsdd[2156]: 2021-11-23 05:46:59,870:wsdd ERROR(pid 2156): error in main loop
Nov 23 05:46:59 pi-backuppc wsdd[2156]: Traceback (most recent call last):
Nov 23 05:46:59 pi-backuppc wsdd[2156]:   File "/usr/bin/wsdd", line 1714, in main
Nov 23 05:46:59 pi-backuppc wsdd[2156]:     key.data.handle_request(key)
Nov 23 05:46:59 pi-backuppc wsdd[2156]:   File "/usr/bin/wsdd", line 212, in handle_request
Nov 23 05:46:59 pi-backuppc wsdd[2156]:     handler.handle_request(msg, address)
Nov 23 05:46:59 pi-backuppc wsdd[2156]:   File "/usr/bin/wsdd", line 727, in handle_request
Nov 23 05:46:59 pi-backuppc wsdd[2156]:     reply = self.handle_message(msg, self.mch, address)
Nov 23 05:46:59 pi-backuppc wsdd[2156]:   File "/usr/bin/wsdd", line 372, in handle_message
Nov 23 05:46:59 pi-backuppc wsdd[2156]:     tree = ElementTree.fromstring(msg)
Nov 23 05:46:59 pi-backuppc wsdd[2156]:   File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
Nov 23 05:46:59 pi-backuppc wsdd[2156]:     parser.feed(text)
Nov 23 05:46:59 pi-backuppc wsdd[2156]:   File "<string>", line None
Nov 23 05:46:59 pi-backuppc wsdd[2156]: xml.etree.ElementTree.ParseError: unbound prefix: line 3, column 17
```
I have no idea what triggers this.     So far it hasn't recurred in the last 3 days.
Let me know if you need more information.
Thanks
Roy

**Comment by christgau** [comment] 2021-11-27 09:53
That's a duplicate of #71 let's continue the discussion there...

**Closed by christgau** 2021-11-27 09:53 UTC
Labels: duplicate

**Comment by christgau** [comment] 2021-11-27 10:45
Please also note that the error message should disappear with v0.7.0 released a week ago.
