### ISSUE TITLE
multiple device announcements

### ISSUE THREAD

**Issue by ewheelerinc** [christgau/wsdd#21] opened 2019-10-10 00:57 UTC
I would like to announce multiple devices from another network segment since the VPN wont forward site-local multicast.

Can wsdd be modified to announce multiple Hostname<->IP devices?

Perhaps it could be provided as a "hosts" file format for a simple first implementation:
```
192.168.10.11   host1
192.168.10.12   host2
...
```

Alternatively, could wsdd implement a proxy such that they could coordinate and forward the announcements?

**Comment by christgau** [comment] 2019-10-10 07:41
That host file-like approach sounds like spoofing service announcements for other hosts ;-) But in fact this is to some extent what the [Discovery Proxy](http://docs.oasis-open.org/ws-dd/discovery/1.1/pr-01/wsdd-discovery-1.1-spec-pr-01.pdf#page=15) (DP) from the spec does. Would such a discovery proxy work for use-case? On [Stackoverflow](https://stackoverflow.com/a/49947754) there has been a discussion with slightly different use-case (discovery across subnets). Additionally there also appears to be an [open source Discovery Proxy](https://archive.codeplex.com/?p=wsdiscoveryproxy) implementation (provided by Microsoft?). Maybe that would work for you. However, the DP - according to the spec - also sends multicasts to announce itself which may prevent using it in your VPN setup.

**Comment by ewheelerinc** [comment] 2019-10-10 18:08
Our ultimate goal is to enumerate our AD DNS records for each network segment.  Lets  say I have the following segments:

- 192.168.10.0/24
- 192.168.11.0/24
- 192.168.12.0/24

Our DNS is at 192.168.10.5. Our goal is to have a local multicast agent (wsdd?) running on each segment that can do a DNS zone transfer from 192.168.10.5 and then announce any A records which are **not** on that segment since hosts on that segment already since local hosts will already announce.

A first pass implementation might be to make a hosts-style list for testing. Integrating DNS would be easy once that is done.

**Comment by christgau** [comment] 2019-10-12 10:22
First off all, web service discovery as implemented in wsdd has nearly nothing to do with DNS. A DNS query might be an implicit step performed during discovery (see [see Figure 5 of the spec](http://docs.oasis-open.org/ws-dd/discovery/1.1/pr-01/wsdd-discovery-1.1-spec-pr-01.pdf#page=18)). But besides that there is no DNS stuff implemented in the software. That is, wsdd is also not capable of doing zone-transfers and that is something out of the project's scope. 

> A first pass implementation might be to make a hosts-style list for testing. Integrating DNS would be easy once that is done.

You could try the https://github.com/nitmir/wsdd fork which allows to specify multiple announced hosts via command line arguments. But I still think that a DP on each non-DNS subnet may work as well. It could be homed in its local subnet, like .11.0 and .12.0 as well as the DNS' subnet (10.0). so it is also discoverable in the latter. Then it should be able to discover all WSD hosts from the three subnets. However, this is only a concept in my mind and I don't know if it really works out as intended.

**Comment by palmtop** [comment] 2020-01-12 07:44
Without knowing that nitmir has already implemented it, I have also implemented the possibility to announce multiple hosts from command line. In my case (https://github.com/palmtop/wsdd) I implemented an additional command line switch: -r host/workgroup to add additional machines. What I see, that the windows 10 client after discovery will display the machine as "host" and when clicking on it it is equivalent to typing "\\host" in windows explorer. (You should make sure that the host is accessible this way.)

In my implementation I have created a remotes list in python which contains the remote machines, so if you have any means to automatically get the list of the remote machines in python (DNS, WSDD Proxy, simple file or anything else) it is very easy to extend this version.

This version is not very much tested, but it works well in my environment.

**Comment by christgau** [comment] 2020-01-12 10:54
@palmtop Do you have the same use case as @ewheelerinc? or do you announce other devices on the same network on behalf of themselves?

**Comment by palmtop** [comment] 2020-01-14 19:43
For me the use case was to add announcements on behalf of an Android phone, which has Samba but no wsdd. (Later it turned out that the phone has other issues as well, so I could not use it). I have 3 more use cases in my plans:

1. For linux machines with samba, I would prefer to have a separate machine with wsdd with announces all of them on the same network, this way, I do not have to install wsdd on all of them.
2. I am planning also to have machines on a different subnet
3. The VPN use case is also valid, simply we do not use VPN that much, so far there was no much need to have hosts displayed in Windows Explorer for VPN.

**Comment by christgau** [comment] 2020-01-17 19:22
Thanks for your contribution. However, besides some style issues I have some technical/conceptual concerns to integrate it. 

>  1. For linux machines with samba, I would prefer to have a separate machine with wsdd with announces all of them on the same network, this way, I do not have to install wsdd on all of them.

When reading the standard it appears to me that the intention is that the "Target Service" (in the end the host offering a file sharing service, in our case) "makes itself available for discovery." For me, this means there should be no "spoofing" in the sense that someone allows a service to be discovered which is not owned/run by that "someone". The only exception from this is a discovery proxy. But as its name suggest it is only a proxy. That is, services still enable their discovery on their own and communicate with the discovery proxy (DP).

Further, by your PR you loose the capability of services/hosts to enter or leave the network. The wsdd instance on the "spoofing host" has no chance to detect that situation. Thus, it would announce hosts that are not up yet/anymore. The only way to update the announced hosts is to restart wsdd. To do so you would have to notice that a samba server has gone or becomes available through any way. So you need to discover such situations, but that's what the discovery is all about.

In addition, I do not understand why installing wsdd on all samba servers is not an option (if I understand it correctly that way). Is it a security concern? If yes, then what are the concerns?

>     2. I am planning also to have machines on a different subnet

IIRC this is actually a valid use case for a DP. [Windows supports that](https://docs.microsoft.com/en-us/windows/win32/wsdapi/additional-ws-discovery-functionality#ws-discovery-v11-cd1-proxy) part of the standard, but I'm not aware of any freely available and working implementation. Maybe wsdd could be extended to perform the required steps. In the feat/discovery branch the client side is implemented, i.e. the "network view" part to list discovered WSD hosts/services. Maybe that's a starting point.

However, as explained above announcing on behalf of other services does not appear to be a valid use case with respect to the standard. Thus, I'm closing this issue as well as the PR. Nevertheless, I'm open for input.

**Closed by christgau** 2020-01-17 19:22 UTC

**Comment by palmtop** [comment] 2020-01-23 06:16
Thank you for spending this much time on this proposal. I see your points, however for me wsdd is a tool to simply add machines to the network neighborhood on all windows machines in my workgroup.

I see two cases when I would add machines manually to it:

1. On the same subnet if there are some technical or practical limitations 
2. On different subnet

In the second case I fully agree that a proxy (may be not the one described in the standard, because according to my understanding that has the goal only to reduce broadcast traffic) would be a correct solution. (I see that I can set the TTL of the broadcast packets, that may also solve this problem). However until the proxy is not available manual machine entry is also a workarround for always available server type machines.

On the first case the reason could be technical, when you have a black box where you can not implement wsdd at all, or administrative. On the linux machines the reason I do not want to install it is that I have a lot of short living test machines and installing wsdd manually is a pain (a simple install script on my side would solve this also).

I also agree that this solution doesn't follow machines entering/leaving the network, in my case these are server type machines which should be always available and it is a smaller problem that the users click on the machine and it is not available than if the machine is not visible in their explorer when it id up and running. (It came to my mind that the program could use ping or something similar to check if the machine is up and running, but I think that this is very much on the hacking side)

But after all, this is your application and it is up to you to drive it into a standard compliant stable version or include "hack" type options.

(After finishing the code, I realized that if I would start again I would use one list for all machines, including the local one and not handle the machines separately from args and remotes.)

**Comment by trostn** [comment] 2024-02-19 23:37
This issue may be a bit older but i still strongly support integrating the changes from nitmir. 

I have a use case where I need to announce different names on different interfaces. I have a device which connects to a WiFi using its hostname but also makes another network interface available through USB using RNDIS.
The WiFi router has a small DNS server running where you can reach other computers on the network by their hostnames. (Fritz Box)
Now, when I disconnect from the WiFi the address resolution will get messed up. 
The router will still resolve the name to the (now unavailable) IP address while the host would still be available on the other interface under a different IP address. But as the (automatically set) metric of the RNDIS interface is higher, the DNS server running there will never be asked as the router still delivers an answer to the name resolution request.
Using another name (like an appended <hostname>.internal) on the RNDIS interface would solve this but this is not yet possible with wsdd as it currently is.
I tried a lot to sort this out but solutions like network namespaces also did not work well or had other limitations (multicasts not getting out, additional IP's ...).
The device using wsdd should work out of the box on other computers and in other networks, so manually setting the metric is also not an option.

Integrating the proposed changes from nitmir would finally solve that. It would be really nice if you integrated them.

**Comment by christgau** [comment] 2024-02-20 21:57
> I have a use case where I need to announce different names on different interfaces [...]
> I tried a lot to sort this out but solutions [...]
> Using another name (like an appended .internal) on the RNDIS interface would solve this but this is not yet possible with wsdd as it currently is.

Have you tried running two instances of wsdd with different arguments, like this (for example) 

```
$ wsdd --interface eth0 --hostname $(hostname).eth0 &
$ wsdd --interface eth1 --hostname $(hostname).eth1 &
```

That should announce two hosts on the respective interfaces, but I cannot test at the moment.

**Comment by trostn** [comment] 2024-02-20 23:31
> Have you tried running two instances of wsdd with different arguments, like this (for example)
> 
> ```
> $ wsdd --interface eth0 --hostname $(hostname).eth0 &
> $ wsdd --interface eth1 --hostname $(hostname).eth1 &
> ```
> 
> That should announce two hosts on the respective interfaces, but I cannot test at the moment.

I did today. It worked somehow (one of the two were visible at a time, removing one network adapter from windows showed the other one then, I guesss that's more a windows thing) but apparently crashed. I am not sure of the reason at the moment and will investigate further.
But indeed I was not using the most recent version of the wsdd script when I wrote that last comment. Now it at least should work.

**Comment by christgau** [comment] 2024-02-21 19:46
> It worked somehow [...] but apparently crashed.

wsdd crashed?! Can you provide a log for this, maybe with `-vv` as command line option?

> (one of the two were visible at a time, removing one network adapter from windows showed the other one then, I guesss that's more a windows thing)

That could also be caused by the UUID sent by wsdd. If you don't specify anything else, internally the UUID is derived either from the hostname or the machine's UUID is used. In the end, the displayed hostname in Explorer is only a label or human-readable alias for the UUID. Thus, you need to provide different UUIDs for the two wsdd instances. 

Try this now:

```
$ wsdd --interface eth0 --hostname $(hostname).eth0 --uuid $(cat /etc/machine-id) &
$ wsdd --interface eth1 --hostname $(hostname).eth1 --uuid $(rev /etc/machine-id) &
``` 

(Usually `/etc/machine-id` exists on most Linux distro installations)

**Comment by trostn** [comment] 2024-02-21 22:47
Hi christgau,

I am sorry, I could not really reproduce the alleged crash.. It seems to be more of a systemd issue. More precisely an OSI layer 8 problem of systemd ;-)

Anyhow, your hint to set different UUIDs did solve my problem, now the two instances of wsdd seem to run correctly. 

If I experience further misbehaviour I can trace back to wsdd I will report back here.

I want to add: I am very happy that you added the option to run wsdd on different interfaces simultaneously, thank you for that and thank you for your work in general. You are doing a great job!
